//! 文件分类器
//!
//! 根据路径和内容将文件分类为 RTL/Testbench/Netlist

use crate::document::FileClass;
use glob::Pattern;

/// 检测内容中是否有 gate-level 实例化特征
/// 网表常见模式: cell_name instance_name ( ... ) 紧随赋值端口
/// 精确匹配大写开头的 cell 名称（AND2, NAND2, DFF, INV 等标准单元命名惯例）
fn has_gate_instances(content: &str) -> bool {
    // 标准网表标志: .assign( 或 .Z(, .Y( 等 cell 端口连接语法
    if content.contains(".Z(") || content.contains(".Y(") || content.contains(".Q(") {
        return true;
    }
    // 常见综合工具添加的网表注释
    if content.contains("// Generated by")
        || content.contains("/* Synthesized")
        || content.contains("synopsys dc_shell")
    {
        return true;
    }
    false
}

/// 文件分类器
pub struct FileClassifier {
    /// RTL 文件模式
    #[allow(dead_code)]
    rtl_patterns: Vec<Pattern>,
    /// 测试平台模式
    tb_patterns: Vec<Pattern>,
    /// 网表模式
    netlist_patterns: Vec<Pattern>,
}

impl FileClassifier {
    /// 创建分类器
    pub fn new() -> Self {
        Self {
            rtl_patterns: vec![
                Pattern::new("*.v").unwrap(),
                Pattern::new("*.sv").unwrap(),
                Pattern::new("*.vh").unwrap(),
                Pattern::new("*.svh").unwrap(),
            ],
            tb_patterns: vec![
                Pattern::new("*_tb.*").unwrap(),
                Pattern::new("*_test.*").unwrap(),
                Pattern::new("tb_*.*").unwrap(),
                Pattern::new("test_*.*").unwrap(),
            ],
            netlist_patterns: vec![
                Pattern::new("*_netlist.*").unwrap(),
                Pattern::new("*_nl.*").unwrap(),
                Pattern::new("*.vg").unwrap(),
            ],
        }
    }

    /// 根据路径分类
    pub fn classify_by_path(&self, path: &str) -> FileClass {
        // 获取文件名
        let filename = path.rsplit('/').next().unwrap_or(path);

        // 先检查网表模式
        for pattern in &self.netlist_patterns {
            if pattern.matches(filename) {
                return FileClass::Netlist;
            }
        }

        // 再检查测试平台模式
        for pattern in &self.tb_patterns {
            if pattern.matches(filename) {
                return FileClass::Testbench;
            }
        }

        // 默认为 RTL
        FileClass::RTL
    }

    /// 根据内容分类
    pub fn classify_by_content(&self, content: &str) -> FileClass {
        // 检查网表特征: 网表有 cell 实例化模式 (gate cells 以 `AND2`, `NAND2`, `DFF` 等开头)
        // SD-2 fix: 使用更精确的模式而非宽泛的 "gate" 子串匹配
        if content.contains("module ") && has_gate_instances(content) {
            return FileClass::Netlist;
        }

        // 检查测试平台特征
        if content.contains("initial begin")
            && (content.contains("$display") || content.contains("$monitor"))
        {
            return FileClass::Testbench;
        }

        FileClass::RTL
    }

    /// 综合分类
    pub fn classify(&self, path: &str, content: &str) -> FileClass {
        let path_class = self.classify_by_path(path);
        let content_class = self.classify_by_content(content);

        // 网表优先级最高
        if path_class == FileClass::Netlist || content_class == FileClass::Netlist {
            return FileClass::Netlist;
        }

        // 测试平台次之
        if path_class == FileClass::Testbench || content_class == FileClass::Testbench {
            return FileClass::Testbench;
        }

        FileClass::RTL
    }
}

impl Default for FileClassifier {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_classify_rtl() {
        let classifier = FileClassifier::new();
        assert_eq!(classifier.classify_by_path("design.sv"), FileClass::RTL);
    }

    #[test]
    fn test_classify_testbench() {
        let classifier = FileClassifier::new();
        assert_eq!(
            classifier.classify_by_path("test_tb.sv"),
            FileClass::Testbench
        );
        assert_eq!(
            classifier.classify_by_path("tb_design.sv"),
            FileClass::Testbench
        );
    }

    #[test]
    fn test_classify_netlist() {
        let classifier = FileClassifier::new();
        assert_eq!(
            classifier.classify_by_path("design_netlist.v"),
            FileClass::Netlist
        );
    }

    #[test]
    fn test_classify_combined_path_wins() {
        let classifier = FileClassifier::new();
        let result = classifier.classify("design_netlist.sv", "module top; endmodule");
        assert_eq!(result, FileClass::Netlist);
    }

    #[test]
    fn test_classify_content_testbench() {
        let classifier = FileClassifier::new();
        let tb_content = "module tb;\ninitial begin\n  $display(\"hello\");\nend\nendmodule";
        assert_eq!(
            classifier.classify_by_content(tb_content),
            FileClass::Testbench
        );
    }

    #[test]
    fn test_classify_vg_extension_is_netlist() {
        let classifier = FileClassifier::new();
        assert_eq!(
            classifier.classify_by_path("synth_out.vg"),
            FileClass::Netlist
        );
    }
}

#[cfg(test)]
mod adversarial_tests {
    use super::*;
    use proptest::prelude::*;

    // 对抗测试: 任意路径的分类结果必须是三选一，不能 panic
    proptest! {
        #[test]
        fn prop_classify_never_panics(path in "[a-z_/\\.]{1,50}") {
            let classifier = FileClassifier::new();
            let result = classifier.classify_by_path(&path);
            prop_assert!(matches!(result, FileClass::RTL | FileClass::Testbench | FileClass::Netlist));
        }

        /// 不变式: 文件分类满足优先级 Netlist > Testbench > RTL
        #[test]
        fn prop_netlist_path_always_netlist(suffix in prop::sample::select(vec!["_netlist.v", "_netlist.sv", "_nl.v", ".vg"])) {
            let classifier = FileClassifier::new();
            let path = format!("design{}", suffix);
            prop_assert_eq!(classifier.classify_by_path(&path), FileClass::Netlist);
        }
    }

    /// SD-2 已修复: RTL 注释中含 "gate" 不再误判为 Netlist
    #[test]
    fn adversarial_gate_word_in_comment_no_longer_misclassified() {
        let classifier = FileClassifier::new();
        let content = "// A 2-input logic gate\nmodule and_gate(input a, b, output y);\n  assign y = a & b;\nendmodule";
        let result = classifier.classify_by_content(content);
        // SD-2 fixed: 不再触发误判
        assert_eq!(
            result,
            FileClass::RTL,
            "SD-2 fixed: gate in comment should classify as RTL"
        );
    }
}
